### ISSUE TITLE
The XHTML Problem

### ISSUE THREAD

**Issue by ayyghost** [Cryptodog/cryptodog#1]
Although we intended to have the web client served as XHTML, I think we should stick to plain HTML for this project. The complexity associated with both

a) making sure the client is served with the proper content-type in extensions
b) dealing with quirks/breakage due to the wrong type being sent or lackluster browser support

outweighs the benefits offered by XHTML, IMO. Furthermore, benefits like faster rendering seem trivial for this project, since there's really only HTML document that gets loaded once per session.

I'm fine with an HTML guideline for consistency's sake (use self-closing tags and double quotes, etc.), but I have yet to see tangible benefits to us mandating XHTML syntax. Thoughts?

**Comment by MullacGeek** [comment]
XHTML can be parsed by HTML browsers/renderers just fine, but the XHTML syntax is much more consistent. Using XHTML will prevent the use of unclosed tags and inline scripts. 

There isn't really any downside to using it aside from the uglier `<html>` tag at the top of the document.

**Comment by ayyghost** [comment]
I've done some more reading, and maybe you're right. The benefit of XHTML enforcing consistent syntax is an important one. We just need to make sure browsers actually know it's XHTML and not text/html.

**Comment by MullacGeek** [comment]
If the webserver is configured right, it should be sent with the correct MIME type. Just need to make sure the file extension is `.xhtml`

**Comment by ayyghost** [comment]
The extension only matters if the document's being accessed from a local filesystem. Over HTTP, all you need is to send the correct content-type header.

**Comment by MullacGeek** [comment]
I'm just thinking of NGINX, which defaults to sending the XHTML MIME-Type
for .xhtml files.

**Comment by ayyghost** [comment]
Okay. I'll still add a <meta> attribute for content-type in the document, just for safety.
