### ISSUE TITLE
Have an option to join a room anonymously

### ISSUE THREAD

**Issue by Lohikar** [Cryptodog/cryptodog#10]
_This issue was recreated from a deleted issue, #3_
Provide a way to join a conversation without having to come up with one, and thus join (more) anonymously
So instead of a custom username, the client could for example set the username to the first few characters your mOTR public key

**Comment by GlasFrost** [comment]
what about a button on the login screen like "random username" which generates a random string or the base64 of a random number and fills it into the username box. this would give the user the chance to sort out nasty words or to say "i don't like that one, gimme a new one" and hit the button again

**Comment by Lohikar** [comment]
We used to have a random username generator that generated names like "anon909", but it was abused.

**Comment by GlasFrost** [comment]
the anonymous login might be abused in a similar way, i guess.

**Comment by Lohikar** [comment]
Maybe just disallow random name gen in lobby?

**Comment by GlasFrost** [comment]
that's not a good solution in my opinion. hiding or disabeling a feature just for the sake of not annoying the developer in a very specific case is just... nah

**Comment by Lohikar** [comment]
Main reason it was removed is people were using it to spam lobby, and the random names make Cryptodog's ignore persistence useless.
