### ISSUE TITLE
Away status not propagated to new users

### ISSUE THREAD

**Issue by Lohikar** [Cryptodog/cryptodog#23]
_This issue is also present in Cryptocat_

If you are marked as away, and someone joins the chat, you will not appear as away to them.

**Comment by Lohikar** [comment]
Tested with freshly cloned repo, away status is _not_ sent to users joining.

Is it not checking for away state on initial connection?

**Comment by ayyghost** [comment]
Could not reproduce. Seems to have been a temporary issue with the server.

**Comment by Lohikar** [comment]
I did some more looking into it, it's a bug localized to Chrome Canary.
Canary is currently completely broken in Cryptodog, so I'm temporarily moving all my testing to another browser.

**Comment by ayyghost** [comment]
Yes, let's use stable browser versions for testing.
