### ISSUE TITLE
Chat history memory leak

### ISSUE THREAD

**Issue by Lohikar** [Cryptodog/cryptodog#24]
When chat is very active, or the client has been open for a while, it can use a significant amount of memory (for a chat client), probably due to the very high amount of elements placed in the DOM for the chat history.

Maybe old chat messages (150 messages ago?) should be dropped from the DOM and moved into a more memory efficient JavaScript string array, and allow the user to re-load messages into the DOM 100 at a time if they need to read the chat history.

**Comment by ayyghost** [comment]
Should be fixed by 994a8e8a03551981a4911fced91a3af1593c69d4, but more testing is needed.

**Comment by ayyghost** [comment]
Update: fixed.
