### ISSUE TITLE
Box does not extend to cover full text on the crypto dog-webclient start page

### ISSUE THREAD

**Issue by AlexanderB-Dev** [Cryptodog/cryptodog#25]
The welcome box at the bottom of the start page does not fully extend down. Because of this the last bit of text is unreadable especially on a dimmer monitor.
![screen shot 2016-01-02 at 5 31 09 pm](https://cloud.githubusercontent.com/assets/16514779/12076569/d3b1ed14-b176-11e5-87c8-72487633d9ec.png)

**Comment by ayyghost** [comment]
Thanks for reporting this. What operating system and browser does this occur on?

**Comment by AlexanderB-Dev** [comment]
OS: Yosemite Version 10.10.5
Browser Safari Version 8.0.8

**Comment by ayyghost** [comment]
I don't have OS X -- can you check if this is resolved, and if not, take another screenshot?

**Comment by AjaxBlue** [comment]
Sure

**Comment by AlexanderB-Dev** [comment]
Great its fixed
