### ISSUE TITLE
Corrupted message warnings look like regular messages

### ISSUE THREAD

**Issue by Lohikar** [Cryptodog/cryptodog#26]
When Cryptodog receives a corrupted message, the corrupted-message warning looks like a regular message.
On Cryptocat, the message box would get a red background and look very different from a regular message.

On Cryptodog, the warning looks like a regular message:
![2016-01-03_12-54-41](https://cloud.githubusercontent.com/assets/7097800/12080208/7bbc1cb2-b219-11e5-8f64-4cf924f4bea1.png)

**Comment by ayyghost** [comment]
Mitigated by 3f94b2c2c6e29f548e319a6b533a654e50bdd509. I'm open to suggestions on how to make it look better.
