### ISSUE TITLE
Unicode allows for nickname abuse

### ISSUE THREAD

**Issue by ayyghost** [Cryptodog/cryptodog#27]
You can impersonate someone who's already online by using the Unicode equivalents of characters in their nickname.

![duplicate](https://cloud.githubusercontent.com/assets/13933477/12527051/10a81456-c143-11e5-9115-354b2dc9c2ef.png)

I'm against prohibiting Unicode nicks server-side, but I do think we should implement a client-side solution. Maybe by adding some visual indication for specific Unicode letters/numbers so users can't be tricked this way. We could just sanitize them the same way we sanitize certain other characters.

**Comment by ayyghost** [comment]
To clarify, the above trick was achieved using Cyrillic Small Letter O (U+043E) and Cyrillic Small Letter A (U+0430) characters.

**Comment by Lohikar** [comment]
Well, the colors in chat _should_ provide a way to differentiate between the two unicode-differentiated people (assuming the gen doesn't make similar colors). Maybe we should show the user color in the buddy list too?

**Comment by ayyghost** [comment]
That may be a good idea, but if we're going to do that, we should also implement deterministically generated colors that are significantly far apart from one another.

Edit: I know you can't 100% enforce color disparity if the generation is deterministic, but something like hash(nickname + fingerprint) should suffice.

**Comment by Lohikar** [comment]
We could keep the random colors, but force the colors to meet a minimum color difference.

**Comment by ayyghost** [comment]
I was thinking determinism because it be easier for more users to have a general consensus as to the identity of someone without manual verification. For example, you verify me, my color is green, so you tell everyone else that green ghost is the real one. Assuming you're also verified.

**Comment by Lohikar** [comment]
How will we enforce enough difference between colors with that method? 

How will we make sure the colors look OK? The current biased random already makes poor colors, hashing would probably pick even worse ones.

**Comment by ayyghost** [comment]
The input entropy (OTR fingerprint) will be great enough to generate disparate enough colors. Does the current random color function use a CSPRNG? As for the aesthetics, that will have to be tweaked with.

**Comment by Lohikar** [comment]
The current method uses `Math.random()`

**Comment by ayyghost** [comment]
Which is awful for generating randomly distributed values.

**Comment by Lohikar** [comment]
Somewhat mitigated in commits 743dd010eafe1333943fafe2cdf23ce39ec2276e and dce9a7deaebbbb4144715e794d03511eeef27d1b. A warning symbol is now displayed beside users who have non-ASCII characters in their names.
