### ISSUE TITLE
Missing size in file send

### ISSUE THREAD

**Issue by Lohikar** [Cryptodog/cryptodog#29]
In the "send encrypted file" dialog, the maximum size of a file you can send _should_ be shown. However, the templating engine seems to not be replacing a string correctly.
![2016-02-14_18-18-55 - 0xdeadbeef lobby_-_google_chrome](https://cloud.githubusercontent.com/assets/7097800/13037508/9244b008-d347-11e5-8003-3f51446dc96a.png)

**Comment by ayyghost** [comment]
It's not replacing it at all. Original Cryptocat locale decoder had a str.replace(). That seems to be missing here.
