### ISSUE TITLE
Sound of notification

### ISSUE THREAD

**Issue by DonaldMorden** [Cryptodog/cryptodog#30]
hello, it's missing the option to have a sound when we receive a message

**Comment by ayyghost** [comment]
Yeah, we originally meant to add sounds back but forgot over the course of time. @MullacGeek will resolve the issue as soon as he can.

**Comment by havano** [comment]
All other sounds in (the old) CryptoCat were purely cosmetic But the incoming message notification sound was crucial for me. It allowed me to divert my attention to other things in between messages. With CryptoDog I have to keep staring at the screen not to miss anything. Very annoying and very tiresome. So please MullacGeek, keep your (or ayyghost's) promise!

**Comment by Lohikar** [comment]
Just a quick update, the backbone of this has been added onto the live version of cryptodog, and a UI for controlling it has been added in commit fbc23bd26d66bc0db18446074bf53d0e7a980225 on master. Probably won't be much longer until it hits live.

**Comment by havano** [comment]
Thanks! 

I will test it later, because the friend I chat with is staying in my house for a week.

Hans

**Comment by havano** [comment]
Hi Lohikar,

Is it live now? If so, what should I do to activate it?

**Comment by Lohikar** [comment]
Sorry for the delay, I've just deployed it now.
Should be available next time you open your client.
