### ISSUE TITLE
Other Cryptocat's problem

### ISSUE THREAD

**Issue by RoPe93** [Cryptodog/cryptodog#31]
It would be nice if there will be a way for users to run their own CryptoDog servers (maybe as Tor H.S).
 Serverside software if you understand.

**Comment by Lohikar** [comment]
You can, just run a Cryptocat server.

The two servers are 100% identical.

https://github.com/cryptocat/cryptocat-legacy/wiki/Server-Deployment-Instructions

**Comment by ayyghost** [comment]
Archived version of aforementioned instructions: https://archive.fo/a7nYO
