### ISSUE TITLE
Some Emoticons are not being displayed

### ISSUE THREAD

**Issue by Shadeclan** [Cryptodog/cryptodog#32]
My friend can get no emoji to work on his copy of CryptoDog except a frowny.  I have :-), :-( and ;-) but :_p doesn't work.  We're both using Google Chrome but it's not the  default browser for either of us, so it's the basic install with the CryptoDog add-on.  My friend did change his default fonts on his computer but it appears that the default fonts in Chrome are the same as mine.

**Comment by Lohikar** [comment]
Are you using different operating systems? Cryptodog doesn't handle emoticons on its own, it relies on the browser/OS to draw them.

**Comment by Shadeclan** [comment]
No - both using Win7.

**Comment by ayyghost** [comment]
Is this still an issue for you? I think it's a Windows 7 font problem. I'm getting the same result as you in Win7, but Win10 works fine.

**Comment by Shadeclan** [comment]
Yeah, it's still happening.
It seems to be inconsistent from computer to computer so it's most certainly a Win7 issue.
