### ISSUE TITLE
Request for Repackaging

### ISSUE THREAD

**Issue by Shadeclan** [Cryptodog/cryptodog#37]
Firefox will be leaving all it's XUL add-ons behind.  Since you've already developed this for Chrome and Firefox is, or soon will be, a Chrome clone, you shouldn't need to modify this much to work on future versions of Firefox.

However, I was wondering if you had the old XUL code lying around.  I use a browser called Pale Moon and it uses XUL add-ons.  Most of Firefox's XUL add-ons work flawlessly in Pale Moon.  I was wondering if you might put out an XPI file for download and installation in Pale Moon?  I am unable to use the recently developed CryptoCat app as I am behind a firewall that prevents the app from connecting to the internet and I can no longer locate the old CryptoCat add-on package.

**Comment by ayyghost** [comment]
We have a copy of the old Cryptocat repo here: https://github.com/Cryptodog/cryptocat

You can use the Makefile to generate an XPI file.

**Comment by Shadeclan** [comment]
Thanks!
