### ISSUE TITLE
AutoBan for "Spammers"

### ISSUE THREAD

**Issue by Peters368** [Cryptodog/cryptodog#40]
Hey people. How about making a character limit, before automatically accusing me of spamming and banning me. That's rude.

**Comment by ayyghost** [comment]
You shouldn't experience this issue anymore (#41).

**Comment by superp00t** [comment]
https://github.com/Cryptodog/cryptodog/commit/791f748e9042f2b5a9ebf5dcf7e24ce999eb77f3
