### ISSUE TITLE
Self hosted cryptodog server

### ISSUE THREAD

**Issue by filirnd** [Cryptodog/cryptodog#42]
Hi ... I need to host server of cryptodog in my own server for security reasons. There is a guide for install it ? Thank's in advance.

**Comment by ayyghost** [comment]
It's just an XMPP server. We use ejabberd. See: https://github.com/Cryptodog/cryptodog/issues/31#issuecomment-265042245 for instructions.

**Comment by filirnd** [comment]
Thank you for answer. I'll try it

**Comment by filirnd** [comment]
I install it (ejabberd ) and install ur frontend on my nginx ws but the frontend link to ur server not to mine. How or where i set ( conf file ?? ) my own ejabberd server ?

**Comment by filirnd** [comment]
I get this error to console log when i try to connect
WebSocket connection to 'wss://192.168.1.x/' failed: Error during WebSocket handshake: Unexpected response code: 200

**Comment by filirnd** [comment]
If i set  port 
WebSocket connection to 'wss://192.168.1.x:5280/' failed: Error in connection establishment: net::ERR_INSECURE_RESPONSE
WrappedWebSocket @ VM100:164

More : 
I install ejabberd, nginx and cryptodog on raspberry pi with raspbian os

**Comment by ayyghost** [comment]
You're probably getting the "Unexpected response code: 200" because you don't have a valid WebSocket endpoint at wss://192.168.1.x/.

Overall, you need to:
1. Enable WebSocket in ejabberd: https://docs.ejabberd.im/admin/configuration/#enabling-websocket-support
2. Configure nginx to pass requests to your WebSocket endpoint to ejabberd. For example:
```
    location /your-websocket-endpoint {
        proxy_buffering off;
        proxy_pass http://192.168.1.x:5280/your-websocket-endpoint;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
```

**Comment by filirnd** [comment]
Hi and thank you for response and patience. I set ejabberd (on ejaberd.yml) like this : 
```
    port: 5280
    ip: "0.0.0.0"
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
    ##  "/pub/archive": mod_http_fileserver
    web_admin: true
    http_bind: true
    ## register: true
    ## captcha: true
    tls: true
    certfile: "/etc/ejabberd/ejabberd.pem"
```
And /etc/nginx/sites-available/default like this : 
```
server  {
        listen 80;
        server_name localhost:80;
        rewrite ^ https://$host:443$request_uri? permanent;
        }

server  {
        add_header Strict-Transport-Security max-age=31536000;
        add_header X-Frame-Options SAMEORIGIN;


        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 5m;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers XXXXXXXX
        ssl_prefer_server_ciphers on;


        listen 443;
        server_name localhost:443;
        ssl on;
        ssl_certificate /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;

        location /              {
                                root /var/www/html;
                                index index.html index.htm;
                                }

        location /http-bind     {
                                proxy_buffering off;
                                proxy_pass http://127.0.0.1:5280/websocket;
                               # proxy_set_header X-Real-IP $remote_addr;
                               # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                               # proxy_set_header Host $http_host;
                                proxy_set_header Upgrade $http_upgrade;
                                proxy_set_header Connection "upgrade";
                               # proxy_redirect off;
                                }
        }

```

But have same error code :
`VM642:164 WebSocket connection to 'wss://192.168.1.166:5280/http-bind' failed: Error during WebSocket handshake: Unexpected response code: 200`

More info : 
If i go to https://192.168.1.166:5280/http-bind i receive page with this info : 
```
ejabberd mod_http_bind

An implementation of XMPP over BOSH (XEP-0206)

This web page is only informative. To use HTTP-Bind you need a Jabber/XMPP client that supports it.
```

I don't understand where is the problem.

**Comment by ayyghost** [comment]
It's because you're using 192.168.1.166:**5280**/http-bind. Try it just with port 443.

You may also want to rename `location /http-bind` to `location /websocket` in the nginx config to avoid confusion. http-bind and websocket are two different ways of connecting to ejabberd.

**Comment by filirnd** [comment]
I set same request_handlers and nginx location at /http-bind and using wss://192.168.1.166:443/http-bind. Now there isn't error from console or network. http-bind return code 101. But in webclient remain in pending "connection.." text.  Can it any problem about anonymous user / chatroom ejabberd side maybe ?

**Comment by ayyghost** [comment]
That's definitely possible, since you're getting the correct HTTP code now. If you post your ejabberd config, I can take a look.

**Comment by filirnd** [comment]
This paste contain my ejabberd config (yml). Thank you
https://paste.fedoraproject.org/paste/Zq7DznGhn8~a9An2WVV39A

**Comment by ayyghost** [comment]
See: https://github.com/cryptodog/docker-cryptodog
