### ISSUE TITLE
Ublock Origin blocking CryptoJS

### ISSUE THREAD

**Issue by superp00t** [Cryptodog/cryptodog#44]
The adblocker [uBlock Origin](https://github.com/gorhill/uBlock) is now blocking Crypto.JS on https://cryptodog.github.io/, which Cryptodog depends on. I suggest we tell users to disable their adblocker while using Cryptodog, or we could find some other kind of workaround.

**Comment by ayyghost** [comment]
This is apparently fixed in development: https://github.com/uBlockOrigin/uAssets/commit/f6a425ac9061a9d14b2840235cbae51dfe018dad

Until it makes its way down, one quick fix is to uncheck "EasyPrivacy" under "3rd-party filters".

**Comment by ayyghost** [comment]
@superp00t This is now resolved; you can re-enable EasyPrivacy.
